import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": "لتستوك",
          "2": "المفضلة",
          "3": " المزعجة",
          "4": "القائمة الرئيسية",
          "5": "تغيير اللون",
          "6": "تسجيل خروج",
          "7": "حذف جميع الرسائل",
          "8": "نقل إلى قائمة",
          "9": "حذف لديَّ فقط",
          "10": "حذف لدى الجميع",
          "11": " إلغاء",
          "12": "تغيير اللغة",
          "13": "هل أنت متأكد؟ ",
          "14": "لا توجد بيانات",
          "15": "نقل إلى القائمة الرئيسية",
          "16": "نقل إلى الرسائل المزعجة",
          "17": "نقل إلى المفضلة",
          "18": "تأكيد",
          "19": "نعم",
          "20": "الرسالة",
          "21": "اللغة العربية",
          "22": "اللغة الإنجليزية",
          'settings': 'إعدادات',
          'date_format_short': 'dd/MM/yyyy',
          'date_format_long': 'd MMMM',
          'online': 'متصل الآن',
          'No Messages Here!': '',
        },
        "en": {
          "1": "Let's Talk",
          "2": "favorits",
          "3": "spam",
          "4": "All messages",
          "5": "Change Color",
          "6": "Sign out",
          "7": "Delete All Messages",
          "8": "Add To List",
          "9": "Delete For You",
          "10": "Delete For Everyone",
          "11": "Cancel",
          "12": "Change Language",
          "13": "Are You Sure?",
          "14": "No Data Found",
          "15": "Move To Main List",
          "16": "Move To Spam",
          "17": "Move To Favorits",
          "18": "confirm",
          "19": "ok",
          "20": 'message',
          "21": "Arabic",
          "22": "English",
          'settings': 'Settings',
          'date_format_short': 'MM/dd/yyyy',
          'date_format_long': 'd MMMM',
          'online': "onine",
          'No Messages Here!': 'No Messages Here!'
        }
      };
}
